server {
    listen 80;
    server_name localhost;
    root /var/www/laravel/public;
    index index.php index.html;

    # Виправлення помилки "upstream sent too big header"
    # Дозволяємо Nginx приймати великі дані (наприклад, від Debugbar)
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;

    # Fix 413s
    client_max_body_size 50M;

    # Serve the Laravel public front controller
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Serve /storage statically
    location ^~ /storage/ {
        alias /var/www/laravel/public/storage/;
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
        disable_symlinks off;
    }

    # PHP handling
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Додаткові тайм-аути (корисно для розробки)
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
    }

    # Hide .ht* files
    location ~ /\.ht {
        deny all;
    }
}